### ISSUE TITLE
Allow for several types/messages per channel

### ISSUE THREAD

**Issue by mikevlz** [rajasimon/beatserver#11]
Hello, first i'd like to thank you for this module.
I would like to have several periodic tasks.  I've thought about grouping them in a specific channel? so the would be all together. But as i see in the code, it's about a single task per channel name.
In order to support different message types in one channel, there should be 2 cycles here https://github.com/rajasimon/beatserver/blob/58feddc3dd2b20ba12a99f51c9a70d6cc7c49b5b/beatserver/server.py#L30
Outer one should cycle through channel name/config(key-value), and inner one should cycle through message types. Or there would be one cycle, but config shoud be a list instead of dictionary(maybe a list of tuples?), so that there could be several items with the same channel name and maybe the same message type.

**Comment by rajasimon** [comment]
Yeah! that would be awesome. And thanks for raising this issue.  I thought it before but my use case for that time simply single type. How about we go with this? 

```
BEAT_SCHEDULE = {
    'testing-print': [
        {
            'type': 'test.check',
            'message': {'foo': 'bar'},
            'schedule': timedelta(seconds=5)
        },
        {
            'type': 'test.print',
            'message': {'foo': 'bar'},
            'schedule': timedelta(seconds=5)
        },
    ]
}
```

**Comment by mikevlz** [comment]
That is a good solution. Any solution would make me happy.
NB: I hope, there will be a check, if "value" is **iterable**, so that simple module update wouldn't break the things

**Comment by mikevlz** [comment]
That is a good solution. Any solution would make me happy.
NB: I hope, there will be a check, if "value" is **iterable**, so that simple module update wouldn't break the things

**Comment by rajasimon** [comment]
I was doing programming challenge and just now having free time. I think channels changed a lot one thing I noticed on my initial run is they removed `channels.log` from the codebase so I'm thinking to create separate logger just for beatserver.

And then I think I can do this work on https://github.com/rajasimon/beatserver/blob/master/beatserver/parser.py#L26 file itself. Somehow just return list of schedule regardless of beatconfig.

**Comment by kylebamos** [comment]
This is also addressed in https://github.com/rajasimon/beatserver/pull/15

**Comment by rajasimon** [comment]
@mikevlz This feature added into v0.0.7. Let us know if you need any help.
