### ISSUE TITLE
Static files are not provided

### ISSUE THREAD

**Issue by kyrgyz-nlp** [rajasimon/beatserver#13]
Hey, thanks for the project! I cloned the repo and tried to run the example, but there are no static files, namely, there is no `websocketbridge.js` file

**Comment by rajasimon** [comment]
Well `websocketbridge` removed in Channels 2 and I'm totally forget to update the examples with the same and thanks for you to raise this issue. 

My suggestion is use <code>[ReconnectingWebSocket](https://github.com/joewalnes/reconnecting-websocket)</code> please find the link below. Please let me know if you can able to run by using this link. I will update this `beatserver` with same. Also PR welcome.

**Comment by rajasimon** [comment]
WebsocketBridge is removed from the original channels because of unstable npm release. Please continue with reconnectingwebsocket. Please let me know if you need any assistance.
