### ISSUE TITLE
Instructions for using in production

### ISSUE THREAD

**Issue by eladyaniv01** [rajasimon/beatserver#18]
Hello,
As i understand, spinning up the beatserver is done separately from spinning up my django server.
So how would i go about using this in production,  if my stack consists of [Gunicorn](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjGlcztiYDvAhWFCuwKHaD1Ds0QFjAAegQIDhAE&url=https%3A%2F%2Fgunicorn.org%2F&usg=AOvVaw2o4sjJRTqdMFL7Ljr0A3sR) + [Daphne](https://github.com/django/daphne) (channels and db already configured with redis channel layer ) 

So for simplicity,  lets say that my current deployment script runs this command 
`sudo systemctl restart gunicorn.service && sudo systemctl restart nginx && sudo systemctl restart daphne.service`

and in my gunicorn config my `ExecStart`  is 
`gunicorn my_app.wsgi --bind 0.0.0.0:8000 --log-level error --log-file=- --workers 5 --preload`

daphne `ExecStart` 
`ExecStart=/home/ubuntu/env/bin/daphne --bind 0.0.0.0 --port <my_port> --verbosity 2 my_app.asgi:application`

how can i also spin up beatserver to play nice with the others ?

**Comment by rajasimon** [comment]
Mmm. I guess it's also very similar to daphne running. Can you try this. 

```
WorkingDirectory=/home/ubuntu/myprojectdir
ExecStart=/home/ubuntu/env/bin/python manage.py beatserver
```

My next update for the beatserver will be a better logging system, Ofcourse with the instructions to run it in the production.
