### ISSUE TITLE
New Logo contribution

### ISSUE THREAD

**Issue by batarian71** [rajasimon/beatserver#7]
Hello, I volunteered a logo to help you. If you like it, I'll send you files. I can design something in line with your wishes. 
![whatsapp image 2018-04-30 at 13 53 04 1](https://user-images.githubusercontent.com/36008612/39431036-319b30ca-4c98-11e8-9ae3-946bc9793088.jpeg)
![whatsapp image 2018-04-30 at 13 53 04](https://user-images.githubusercontent.com/36008612/39431037-31f1af54-4c98-11e8-9cc3-ecccb51001d7.jpeg)
![whatsapp image 2018-04-30 at 13 53 05](https://user-images.githubusercontent.com/36008612/39431038-321a077e-4c98-11e8-871d-0d2fceda02ad.jpeg)
![whatsapp image 2018-04-30 at 13 53 06](https://user-images.githubusercontent.com/36008612/39431039-3249c8ce-4c98-11e8-8057-700a10319526.jpeg)

Which one did you like ?

**Comment by rajasimon** [comment]
I like the first row second the green one. PR welcome.

**Comment by batarian71** [comment]
Can you check it? I sent pullrequest.

https://github.com/rajasimon/beatserver/pull/8

**Comment by rajasimon** [comment]
Thanks 👍
