### ISSUE TITLE
how can I run beatserver

### ISSUE THREAD

**Issue by RealLau** [rajasimon/beatserver#9]
After installed with command pip3 install -U beatserver, OS can not recognize command 'beatserver' on OSX.
BTW, beatserver is a websocket server which can continuely send message to clients browser frontend if I didn't make any misunderstanding?

**Comment by rajasimon** [comment]
Sorry for the delay response.  To be clear beatserver is Django app that you can install and plug into your Django project and this helps you to send message continually to the client browser.  Please follow below procedure for how to run beatserver.  

1. Install beatserver
2. Add beatserver to your installed apps
3. Write your consumer function like this...

```
class PrintConsumer(SyncConsumer):

    def test_print(self, message):
        print(message)

```
4. Create a file called `beatconfig.py` in your project directory. And configure it like this
```
from datetime import timedelta

BEAT_SCHEDULE = {
    'testing-print': {
        'type': 'test.print',
        'message': {'foo': 'bar'},
        'schedule': timedelta(seconds=5)
    },
}
```

5. `python manage.py runserver` 

And make sure you have the latest version.  If this not works let me know I'm happy to help.

**Comment by rajasimon** [comment]
Note that my prev comment helps you to configure beatserver on your Django project. But if you want to send a message to client browser you need to send another message to the group and then broadcast message to the client browser. 
```
class PrintConsumer(SyncConsumer):

    def test_print(self, message):
        async_to_sync(
            channel_layer.group_send)("<group_name>", {
                    "type": "<target.function>",
                    "message": "<your message here"
                }
         )

        print(message)
```

Still, I'm not sure how to send a message back to the client without group because we don't know about the `channel_name`

**Comment by RealLau** [comment]
Thanks for the reply, and could you please help check the config and code as below, currently it's not work:
**beatconfig.py**
```
from datetime import timedelta

BEAT_SCHEDULE = {
    'testing-print': {
        'type': 'test.print',
        'message': {'message': 'UUUU'},
        'schedule': timedelta(seconds=5)
    },
}
```
**consumers.py**
```
from channels.generic.websocket import AsyncWebsocketConsumer, SyncConsumer, async_to_sync
import json

class ServiceConsumer(AsyncWebsocketConsumer):
    async def connect(self):
        self.project_pk = self.scope['url_route']['kwargs']['project_pk']
        self.room_group_name = 'status_%s' % self.project_pk
        # Join room group
        await self.channel_layer.group_add(
            self.room_group_name,
            self.channel_name
        )
        await self.accept()


    async def disconnect(self, close_code):
        # Leave room group
        await self.channel_layer.group_discard(
            self.room_group_name,
            self.channel_name
        )

    # Receive message from WebSocket
    async def receive(self, text_data):
        text_data_json = json.loads(text_data)
        message = text_data_json['message']

        # Send message to room group
        await self.channel_layer.group_send(
            self.room_group_name,
            {
                'type': 'status_message',
                'message': message
            }
        )

    # Receive message from room group
    async def status_message(self, event):
        # todo: get real status from service detection api
        message = event['message']

        # Send message to WebSocket
        await self.send(text_data=json.dumps({
            'message': message
        }))

    def test_print(self, message):
        async_to_sync(self.channel_layer.group_send)(self.room_group_name, {
            "type": "status_message",
            "message": "Update"
        })
        print(message)
```
**routing.py**
```from channels.auth import AuthMiddlewareStack
from channels.routing import ProtocolTypeRouter, URLRouter, ChannelNameRouter
import autoplatform.routing
from autoplatform import consumers

application = ProtocolTypeRouter({
    # (http->django views is added by default)
    'websocket': AuthMiddlewareStack(
        URLRouter(
            autoplatform.routing.websocket_urlpatterns
        )
    ),
    "channel": ChannelNameRouter({
        "service-detection": consumers.ServiceConsumer,
        "testing-print": consumers.ServiceConsumer
    }),
})
```
**Note** 
1. what I want to see is, after browser client connected to server, server will continuously send message to client. For now, I'll have to click a button on the frontend page and get only one message response back ;
2. I noticed that there's strange config in **beatconfig.py**:
`testing-print` and `test.print` what are these 2 config name for? Is it just lapsus calami? I mean the function name in **consumer.py** is `test_print`, so...why?

**Comment by rajasimon** [comment]
To answer your `Note` question...

> I noticed that there's strange config in beatconfig.py:
testing-print and test.print what are these 2 config name for? Is it just lapsus calami? I mean the function name in consumer.py is test_print, so...why?

`testing-print` is channel name router name. And `test.print` is the function inside that consumer. Channel will convert that `test.print` to `test_print`

-----

Remember that Channels 2 `websocket` and `channel` router work differently. You can't send background message to  `WebsocketConsumer`, It's for Websockets only ( Client <=> Server ) and you can't interfere in between this. 

What you can do is Create another class based Simple consumer function, either using SyncConsumer or AsyncConsumer ( Whatever you can use ). And hook to `ChannelNameRouter` so beatserver can fire events this consumer. 

And finally, you have to send the message to Group. And the group will push message to the browser. 

```
class TestingConsumer(SyncConsumer):

    def test_print(self, event):
        async_to_sync(self.channel_layer.group_send)("status_<id>", {"type": "test.print", 'message': "hello world"})

```

Right now I've working example demo version of what you are asking. Give me a minutes to upload. Let me know if this clears your doubt.

**Comment by rajasimon** [comment]
I've pushed working example that push message to browser periodically. 58feddc

**Comment by RealLau** [comment]
Thanks @rajasimon this helps a lot! And, finally I've make it OK!
